export function convert(code) {
        let text = "";
        switch(code)
        {
            case ".-": text = "A";
            break;
            case "-...": text = "B";
            break;
            case "-.-.": text = "C";
            break;
            case "-..": text = "D";
            break;
            case ".": text = "E";
            break;
            case "--.": text = "F";
            break;
            case "--.": text = "G";
            break;
            case "....": text = "H";
            break;
            case "..": text = "I";
            break;
            case ".---": text = "J";
            break;
            case "-.-": text = "K";
            break;
            case ".-..": text = "L";
            break;
            case "--": text = "M";
            break;
            case "-.": text = "N";
            break;
            case "---": text = "O";
            break;
            case ".--.": text = "P";
            break;
            case "--.-": text = "Q";
            break;
            case ".-.": text = "R";
            break;
            case "...": text = "S";
            break;
            case "-": text = "T";
            break;
            case "..-": text = "U";
            break;
            case "...-": text = "V";
            break;
            case ".--": text = "W";
            break;
            case "-..-": text = "X";
            break;
            case "-.--": text = "Y";
            break;
            case "--..": text = "Z";
            break;
            case ".----": text = "1";
            break;
            case "..---": text = "2";
            break;
            case "...--": text = "3";
            break;
            case "....-": text = "4";
            break;
            case ".....": text = "5";
            break;
            case "-....": text = "6";
            break;
            case "--...": text = "7";
            break;
            case "---..": text = "8";
            break;
            case "----.": text = "9";
            break;
            case "-----": text = "0";
            break;
        }    
        return text;
    }
